#!/usr/bin/env bash
# Transfers a file from our client to a server

file_path="$1"
server_ip="$2"
username="$3"
path_to_ssh_key="$4"

if scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$file_path" "$username@$server_ip":~/;
then
    echo "$username@$server_ip:~/"
else
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
