#!/usr/bin/env bash
# Configures an Nginx server with a custom 404 page

apt-get update
apt-get install -y nginx

# Create the directory for custom error pages
mkdir -p /etc/nginx/html/errors

# Create a custom 404 page with the desired string
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/errors/404.html

# Create a custom Nginx configuration file for the custom error page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /etc/nginx/html;
    index index.html index.htm;

    error_page 404 /errors/404.html;

    location /errors {
        alias /etc/nginx/html/errors;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Enable the new site configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Test Nginx configuration and reload
sudo nginx -t
sudo service nginx reload
