#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements:
# name of the custom HTTP header must be X-Served-By
# value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt-get update

sudo apt-get install -y nginx

# Start Nginx service
sudo service nginx start

# Enable Nginx to start on boot
sudo update-rc.d nginx defaults

# Nginx listening on port 80
sudo bash -c "cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        root /var/www/html;
        index index.html;
	# custom HTTP response header
	add_header X-Served-By \$(hostname);
    }
}
EOF"

# Reload Nginx to apply the changes
sudo service nginx reload
