#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements:
# name of the custom HTTP header must be X-Served-By
# value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt-get update

sudo apt-get install -y nginx
# Start Nginx service
sudo service nginx start

# Enable Nginx to start on boot
sudo update-rc.d nginx defaults

SERVER=$(hostname)

SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
		add_header X-Served-By '$SERVER';
                try_files \$uri \$uri/ =404;
        }
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

sudo /etc/init.d/nginx restart
