#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

# Update package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo bash -c "cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend web_front
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server web-01 329327-web-01:80 check
    server web-02 329327-web-02:80 check
EOF"

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Restart HAProxy to apply changes
sudo systemctl restart haproxy
