#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

# Update package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# edit config file
server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 329327-web-01 54.146.65.170:80 check
        server 329327-web-02 100.25.26.229:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
