#!/usr/bin/env bash
# configures a server to run and listen on port 80

# remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart Nginx
service nginx restart
