#!/usr/bin/env bash
# Script:
# Creates the file /var/run/myscript.pid containing its PID
# displays To infinity and beyond indefinitely
# displays I hate the kill command when receiving a SIGTERM signal
# displays Y U no love me?! when receiving a SIGINT signal
# deletes the file /var/run/myscript.pid and terminates itself when
# receiving a SIGQUIT or SIGTERM signal

term()
{
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do

	echo "To infinity and beyond"
	sleep 2
	trap "echo 'Y U no love me?!'" SIGINT
	trap "echo 'I hate the kill command' && term" SIGTERM
	trap "term" SIGQUIT
done
