#!/usr/bin/env bash
# This script displays numbers from 1 to 100:
# displays FizzBuzz when the number is a multiple of 3 and 5
# displays Fizz when the number is multiple of 3
# displays Buzz when the number is a multiple of 5
# otherwise, displays the number in a list format

number=100
for ((i = 1; i <= number; i++))
do
	if (( i % 3 == 0)) && ((i % 5 == 0))
        then
                echo "FizzBuzz"
        elif ((i % 3 == 0))
        then
                echo "Fizz"
        elif ((i % 5 == 0))
        then
                echo "Buzz"
        else
                echo $i
        fi
done
