#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd:
# username
# user id
# home directory path for the user

while read -r name
do
	echo "$name" | cut -d":" -f1,4,6
done < /etc/passwd
