#!/usr/bin/env bash
# configures a container to run Nginx as nginx user

chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2

# Restart Nginx
su nginx -s /bin/bash -c 'service nginx restart'
#service nginx restart
